package mnj.ont.model.services.common;

import oracle.jbo.ApplicationModule;
import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 05 15:59:31 BDT 2017
// ---------------------------------------------------------------------
public interface MainAM extends ApplicationModule {
    void populateBpoLines1(String param);

    void populateBPOLines(Row param);

    String getPopulateValue(Row param, String param2);

    String getOrgId();

    Row createBPOLines();

    void callBpoFetch();

    void SetTotalValue(String param);

    void setSessionValues(String param, String param2, String param3,
                          String param4);

    int pinovalidation(String param);

    String getRespKey(String param);



    void populateDetails(String po, String orgID);

    String getSuppId();

    String getCurrency();

    Row createDetails();
}
