package mnj.ont.model.services.client;

import mnj.ont.model.services.common.MainAM;

import oracle.jbo.Row;
import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 26 18:11:35 BDT 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MainAMClient extends ApplicationModuleImpl implements MainAM {
    /**
     * This is the default constructor (do not remove).
     */
    public MainAMClient() {
    }


    public void setSessionValues(String orgId, String userId, String respId,
                                 String respAppl) {
        Object _ret =
            this.riInvokeExportedMethod(this,"setSessionValues",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {orgId, userId, respId, respAppl});
        return;
    }

    public void populateDetails(String po, String orgID) {
        Object _ret =
            this.riInvokeExportedMethod(this,"populateDetails",new String [] {"java.lang.String","java.lang.String"},new Object[] {po, orgID});
        return;
    }

    public void populateBpoLines1(String OrgId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"populateBpoLines1",new String [] {"java.lang.String"},new Object[] {OrgId});
        return;
    }

    public void populateBPOLines(Row poprow) {
        Object _ret =
            this.riInvokeExportedMethod(this,"populateBPOLines",new String [] {"oracle.jbo.Row"},new Object[] {poprow});
        return;
    }

    public int pinovalidation(String bblcnumber) {
        Object _ret =
            this.riInvokeExportedMethod(this,"pinovalidation",new String [] {"java.lang.String"},new Object[] {bblcnumber});
        return ((Integer)_ret).intValue();
    }

    public String getSuppId() {
        Object _ret = this.riInvokeExportedMethod(this,"getSuppId",null,null);
        return (String)_ret;
    }

    public String getRespKey(String respId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getRespKey",new String [] {"java.lang.String"},new Object[] {respId});
        return (String)_ret;
    }

    public String getPopulateValue(Row r, String columnName) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getPopulateValue",new String [] {"oracle.jbo.Row","java.lang.String"},new Object[] {r, columnName});
        return (String)_ret;
    }

    public String getOrgId() {
        Object _ret = this.riInvokeExportedMethod(this,"getOrgId",null,null);
        return (String)_ret;
    }

    public String getCurrency() {
        Object _ret = this.riInvokeExportedMethod(this,"getCurrency",null,null);
        return (String)_ret;
    }

    public Row createDetails() {
        Object _ret = this.riInvokeExportedMethod(this,"createDetails",null,null);
        return (Row)_ret;
    }

    public Row createBPOLines() {
        Object _ret = this.riInvokeExportedMethod(this,"createBPOLines",null,null);
        return (Row)_ret;
    }

    public void callBpoFetch() {
        Object _ret = this.riInvokeExportedMethod(this,"callBpoFetch",null,null);
        return;
    }

    public void SetTotalValue(String TotalVal) {
        Object _ret =
            this.riInvokeExportedMethod(this,"SetTotalValue",new String [] {"java.lang.String"},new Object[] {TotalVal});
        return;
    }
}
