package mnj.ont.model.views;

import oracle.jbo.domain.Date;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 26 15:27:29 BDT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ImpPiLinesVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ImpPiLinesVOImpl() {
    }

    /**
     * Returns the variable value for PiNumber.
     * @return variable value for PiNumber
     */
    public String getPiNumber() {
        return (String)ensureVariableManager().getVariableValue("PiNumber");
    }

    /**
     * Sets <code>value</code> for variable PiNumber.
     * @param value value to bind as PiNumber
     */
    public void setPiNumber(String value) {
        ensureVariableManager().setVariableValue("PiNumber", value);
    }

    /**
     * Returns the variable value for PiDateSearch.
     * @return variable value for PiDateSearch
     */
    public Date getPiDateSearch() {
        return (Date)ensureVariableManager().getVariableValue("PiDateSearch");
    }

    /**
     * Sets <code>value</code> for variable PiDateSearch.
     * @param value value to bind as PiDateSearch
     */
    public void setPiDateSearch(Date value) {
        ensureVariableManager().setVariableValue("PiDateSearch", value);
    }
}
