package mnj.ont.model.views;

import mnj.ont.model.entities.ImpPiLinesEOImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 26 15:27:29 BDT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ImpPiLinesVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        ImpPiLineId {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getImpPiLineId();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setImpPiLineId((Number)value);
            }
        }
        ,
        ImpPiHeaderId {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getImpPiHeaderId();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setImpPiHeaderId((Number)value);
            }
        }
        ,
        PiNo {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getPiNo();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setPiNo((String)value);
            }
        }
        ,
        PiDate {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getPiDate();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setPiDate((Date)value);
            }
        }
        ,
        Currency {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getCurrency();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setCurrency((String)value);
            }
        }
        ,
        TotalValue {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getTotalValue();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setTotalValue((Number)value);
            }
        }
        ,
        EstimatedShipDate {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getEstimatedShipDate();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setEstimatedShipDate((Date)value);
            }
        }
        ,
        PaymentTerm {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getPaymentTerm();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setPaymentTerm((String)value);
            }
        }
        ,
        SupplierId {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getSupplierId();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setSupplierId((Number)value);
            }
        }
        ,
        DischargePort {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getDischargePort();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setDischargePort((String)value);
            }
        }
        ,
        ShipPort {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getShipPort();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setShipPort((String)value);
            }
        }
        ,
        HsCode {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getHsCode();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setHsCode((String)value);
            }
        }
        ,
        StandardTransitTime {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getStandardTransitTime();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setStandardTransitTime((String)value);
            }
        }
        ,
        ExMillDate {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getExMillDate();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setExMillDate((Date)value);
            }
        }
        ,
        ExCountryDate {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getExCountryDate();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setExCountryDate((Date)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setLastUpdateLogin((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        Attribute1 {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getAttribute1();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getAttribute2();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getAttribute3();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getAttribute4();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getAttribute5();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getAttribute6();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getAttribute7();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getAttribute8();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getAttribute9();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getAttribute10();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getAttribute11();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getAttribute12();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getAttribute13();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getAttribute14();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getAttribute15();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        Attribute16 {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getAttribute16();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setAttribute16((String)value);
            }
        }
        ,
        Attribute17 {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getAttribute17();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setAttribute17((String)value);
            }
        }
        ,
        Attribute18 {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getAttribute18();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setAttribute18((String)value);
            }
        }
        ,
        Attribute19 {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getAttribute19();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setAttribute19((String)value);
            }
        }
        ,
        Attribute20 {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getAttribute20();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setAttribute20((String)value);
            }
        }
        ,
        Attribute21 {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getAttribute21();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setAttribute21((String)value);
            }
        }
        ,
        Attribute22 {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getAttribute22();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setAttribute22((String)value);
            }
        }
        ,
        Attribute23 {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getAttribute23();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setAttribute23((String)value);
            }
        }
        ,
        Attribute24 {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getAttribute24();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setAttribute24((String)value);
            }
        }
        ,
        Attribute25 {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getAttribute25();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setAttribute25((String)value);
            }
        }
        ,
        Attribute26 {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getAttribute26();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setAttribute26((String)value);
            }
        }
        ,
        Attribute27 {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getAttribute27();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setAttribute27((String)value);
            }
        }
        ,
        Attribute28 {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getAttribute28();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setAttribute28((String)value);
            }
        }
        ,
        Attribute29 {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getAttribute29();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setAttribute29((String)value);
            }
        }
        ,
        Attribute30 {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getAttribute30();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setAttribute30((String)value);
            }
        }
        ,
        OrgId {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getOrgId();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        PiDocNumber {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getPiDocNumber();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setPiDocNumber((Number)value);
            }
        }
        ,
        VersionDate {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getVersionDate();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setVersionDate((Date)value);
            }
        }
        ,
        VersionNumber {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getVersionNumber();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setVersionNumber((Number)value);
            }
        }
        ,
        DeliveryDate {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getDeliveryDate();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setDeliveryDate((Date)value);
            }
        }
        ,
        ReceivedDate {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getReceivedDate();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setReceivedDate((Date)value);
            }
        }
        ,
        BblcNo {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getBblcNo();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setBblcNo((String)value);
            }
        }
        ,
        SpoNos {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getSpoNos();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setSpoNos((String)value);
            }
        }
        ,
        SpoBuyer {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getSpoBuyer();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setSpoBuyer((String)value);
            }
        }
        ,
        SpoSeason {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getSpoSeason();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setSpoSeason((String)value);
            }
        }
        ,
        OrgName {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getOrgName();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setOrgName((String)value);
            }
        }
        ,
        Supplier {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getSupplier();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setSupplier((String)value);
            }
        }
        ,
        CreatedByName {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getCreatedByName();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setCreatedByName((String)value);
            }
        }
        ,
        ReceivingDelay {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getReceivingDelay();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setReceivingDelay((Number)value);
            }
        }
        ,
        LcEnteringDate {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getLcEnteringDate();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setLcEnteringDate((Date)value);
            }
        }
        ,
        LcEnteringDealy {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getLcEnteringDealy();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setLcEnteringDealy((Number)value);
            }
        }
        ,
        ImpPiDetails {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getImpPiDetails();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ImpPiAdjustments {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getImpPiAdjustments();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ItemQtyDetail {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getItemQtyDetail();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        FillBPO {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getFillBPO();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SuppVO1 {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getSuppVO1();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CustomerVO1 {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getCustomerVO1();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        SupplierVO1 {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getSupplierVO1();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        CurrencyVO1 {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getCurrencyVO1();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        OrgVO1 {
            public Object get(ImpPiLinesVORowImpl obj) {
                return obj.getOrgVO1();
            }

            public void put(ImpPiLinesVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;

        private static int firstIndex = 0;

        public abstract Object get(ImpPiLinesVORowImpl object);

        public abstract void put(ImpPiLinesVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IMPPILINEID = AttributesEnum.ImpPiLineId.index();
    public static final int IMPPIHEADERID = AttributesEnum.ImpPiHeaderId.index();
    public static final int PINO = AttributesEnum.PiNo.index();
    public static final int PIDATE = AttributesEnum.PiDate.index();
    public static final int CURRENCY = AttributesEnum.Currency.index();
    public static final int TOTALVALUE = AttributesEnum.TotalValue.index();
    public static final int ESTIMATEDSHIPDATE = AttributesEnum.EstimatedShipDate.index();
    public static final int PAYMENTTERM = AttributesEnum.PaymentTerm.index();
    public static final int SUPPLIERID = AttributesEnum.SupplierId.index();
    public static final int DISCHARGEPORT = AttributesEnum.DischargePort.index();
    public static final int SHIPPORT = AttributesEnum.ShipPort.index();
    public static final int HSCODE = AttributesEnum.HsCode.index();
    public static final int STANDARDTRANSITTIME = AttributesEnum.StandardTransitTime.index();
    public static final int EXMILLDATE = AttributesEnum.ExMillDate.index();
    public static final int EXCOUNTRYDATE = AttributesEnum.ExCountryDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int ATTRIBUTE16 = AttributesEnum.Attribute16.index();
    public static final int ATTRIBUTE17 = AttributesEnum.Attribute17.index();
    public static final int ATTRIBUTE18 = AttributesEnum.Attribute18.index();
    public static final int ATTRIBUTE19 = AttributesEnum.Attribute19.index();
    public static final int ATTRIBUTE20 = AttributesEnum.Attribute20.index();
    public static final int ATTRIBUTE21 = AttributesEnum.Attribute21.index();
    public static final int ATTRIBUTE22 = AttributesEnum.Attribute22.index();
    public static final int ATTRIBUTE23 = AttributesEnum.Attribute23.index();
    public static final int ATTRIBUTE24 = AttributesEnum.Attribute24.index();
    public static final int ATTRIBUTE25 = AttributesEnum.Attribute25.index();
    public static final int ATTRIBUTE26 = AttributesEnum.Attribute26.index();
    public static final int ATTRIBUTE27 = AttributesEnum.Attribute27.index();
    public static final int ATTRIBUTE28 = AttributesEnum.Attribute28.index();
    public static final int ATTRIBUTE29 = AttributesEnum.Attribute29.index();
    public static final int ATTRIBUTE30 = AttributesEnum.Attribute30.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int PIDOCNUMBER = AttributesEnum.PiDocNumber.index();
    public static final int VERSIONDATE = AttributesEnum.VersionDate.index();
    public static final int VERSIONNUMBER = AttributesEnum.VersionNumber.index();
    public static final int DELIVERYDATE = AttributesEnum.DeliveryDate.index();
    public static final int RECEIVEDDATE = AttributesEnum.ReceivedDate.index();
    public static final int BBLCNO = AttributesEnum.BblcNo.index();
    public static final int SPONOS = AttributesEnum.SpoNos.index();
    public static final int SPOBUYER = AttributesEnum.SpoBuyer.index();
    public static final int SPOSEASON = AttributesEnum.SpoSeason.index();
    public static final int ORGNAME = AttributesEnum.OrgName.index();
    public static final int SUPPLIER = AttributesEnum.Supplier.index();
    public static final int CREATEDBYNAME = AttributesEnum.CreatedByName.index();
    public static final int RECEIVINGDELAY = AttributesEnum.ReceivingDelay.index();
    public static final int LCENTERINGDATE = AttributesEnum.LcEnteringDate.index();
    public static final int LCENTERINGDEALY = AttributesEnum.LcEnteringDealy.index();
    public static final int IMPPIDETAILS = AttributesEnum.ImpPiDetails.index();
    public static final int IMPPIADJUSTMENTS = AttributesEnum.ImpPiAdjustments.index();
    public static final int ITEMQTYDETAIL = AttributesEnum.ItemQtyDetail.index();
    public static final int FILLBPO = AttributesEnum.FillBPO.index();
    public static final int SUPPVO1 = AttributesEnum.SuppVO1.index();
    public static final int CUSTOMERVO1 = AttributesEnum.CustomerVO1.index();
    public static final int SUPPLIERVO1 = AttributesEnum.SupplierVO1.index();
    public static final int CURRENCYVO1 = AttributesEnum.CurrencyVO1.index();
    public static final int ORGVO1 = AttributesEnum.OrgVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ImpPiLinesVORowImpl() {
    }

    /**
     * Gets ImpPiLinesEO entity object.
     * @return the ImpPiLinesEO
     */
    public ImpPiLinesEOImpl getImpPiLinesEO() {
        return (ImpPiLinesEOImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for IMP_PI_LINE_ID using the alias name ImpPiLineId.
     * @return the IMP_PI_LINE_ID
     */
    public Number getImpPiLineId() {
        return (Number) getAttributeInternal(IMPPILINEID);
    }

    /**
     * Sets <code>value</code> as attribute value for IMP_PI_LINE_ID using the alias name ImpPiLineId.
     * @param value value to set the IMP_PI_LINE_ID
     */
    public void setImpPiLineId(Number value) {
        setAttributeInternal(IMPPILINEID, value);
    }

    /**
     * Gets the attribute value for IMP_PI_HEADER_ID using the alias name ImpPiHeaderId.
     * @return the IMP_PI_HEADER_ID
     */
    public Number getImpPiHeaderId() {
        return (Number) getAttributeInternal(IMPPIHEADERID);
    }

    /**
     * Sets <code>value</code> as attribute value for IMP_PI_HEADER_ID using the alias name ImpPiHeaderId.
     * @param value value to set the IMP_PI_HEADER_ID
     */
    public void setImpPiHeaderId(Number value) {
        setAttributeInternal(IMPPIHEADERID, value);
    }

    /**
     * Gets the attribute value for PI_NO using the alias name PiNo.
     * @return the PI_NO
     */
    public String getPiNo() {
        return (String) getAttributeInternal(PINO);
    }

    /**
     * Sets <code>value</code> as attribute value for PI_NO using the alias name PiNo.
     * @param value value to set the PI_NO
     */
    public void setPiNo(String value) {
        setAttributeInternal(PINO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BblcNo.
     * @return the BblcNo
     */
    public String getBblcNo() {
        return (String) getAttributeInternal(BBLCNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BblcNo.
     * @param value value to set the  BblcNo
     */
    public void setBblcNo(String value) {
        setAttributeInternal(BBLCNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SpoNos.
     * @return the SpoNos
     */
    public String getSpoNos() {
        return (String) getAttributeInternal(SPONOS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SpoNos.
     * @param value value to set the  SpoNos
     */
    public void setSpoNos(String value) {
        setAttributeInternal(SPONOS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SpoBuyer.
     * @return the SpoBuyer
     */
    public String getSpoBuyer() {
        return (String) getAttributeInternal(SPOBUYER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SpoBuyer.
     * @param value value to set the  SpoBuyer
     */
    public void setSpoBuyer(String value) {
        setAttributeInternal(SPOBUYER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SpoSeason.
     * @return the SpoSeason
     */
    public String getSpoSeason() {
        return (String) getAttributeInternal(SPOSEASON);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SpoSeason.
     * @param value value to set the  SpoSeason
     */
    public void setSpoSeason(String value) {
        setAttributeInternal(SPOSEASON, value);
    }

    /**
     * Gets the attribute value for PI_DATE using the alias name PiDate.
     * @return the PI_DATE
     */
    public Date getPiDate() {
        return (Date) getAttributeInternal(PIDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for PI_DATE using the alias name PiDate.
     * @param value value to set the PI_DATE
     */
    public void setPiDate(Date value) {
        setAttributeInternal(PIDATE, value);
    }

    /**
     * Gets the attribute value for CURRENCY using the alias name Currency.
     * @return the CURRENCY
     */
    public String getCurrency() {
        return (String) getAttributeInternal(CURRENCY);
    }

    /**
     * Sets <code>value</code> as attribute value for CURRENCY using the alias name Currency.
     * @param value value to set the CURRENCY
     */
    public void setCurrency(String value) {
        setAttributeInternal(CURRENCY, value);
    }

    /**
     * Gets the attribute value for TOTAL_VALUE using the alias name TotalValue.
     * @return the TOTAL_VALUE
     */
    public Number getTotalValue() {
        return (Number) getAttributeInternal(TOTALVALUE);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_VALUE using the alias name TotalValue.
     * @param value value to set the TOTAL_VALUE
     */
    public void setTotalValue(Number value) {
        setAttributeInternal(TOTALVALUE, value);
    }

    /**
     * Gets the attribute value for ESTIMATED_SHIP_DATE using the alias name EstimatedShipDate.
     * @return the ESTIMATED_SHIP_DATE
     */
    public Date getEstimatedShipDate() {
        return (Date) getAttributeInternal(ESTIMATEDSHIPDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for ESTIMATED_SHIP_DATE using the alias name EstimatedShipDate.
     * @param value value to set the ESTIMATED_SHIP_DATE
     */
    public void setEstimatedShipDate(Date value) {
        setAttributeInternal(ESTIMATEDSHIPDATE, value);
    }

    /**
     * Gets the attribute value for PAYMENT_TERM using the alias name PaymentTerm.
     * @return the PAYMENT_TERM
     */
    public String getPaymentTerm() {
        return (String) getAttributeInternal(PAYMENTTERM);
    }

    /**
     * Sets <code>value</code> as attribute value for PAYMENT_TERM using the alias name PaymentTerm.
     * @param value value to set the PAYMENT_TERM
     */
    public void setPaymentTerm(String value) {
        setAttributeInternal(PAYMENTTERM, value);
    }

    /**
     * Gets the attribute value for SUPPLIER_ID using the alias name SupplierId.
     * @return the SUPPLIER_ID
     */
    public Number getSupplierId() {
        return (Number) getAttributeInternal(SUPPLIERID);
    }

    /**
     * Sets <code>value</code> as attribute value for SUPPLIER_ID using the alias name SupplierId.
     * @param value value to set the SUPPLIER_ID
     */
    public void setSupplierId(Number value) {
        setAttributeInternal(SUPPLIERID, value);
    }

    /**
     * Gets the attribute value for DISCHARGE_PORT using the alias name DischargePort.
     * @return the DISCHARGE_PORT
     */
    public String getDischargePort() {
        return (String) getAttributeInternal(DISCHARGEPORT);
    }

    /**
     * Sets <code>value</code> as attribute value for DISCHARGE_PORT using the alias name DischargePort.
     * @param value value to set the DISCHARGE_PORT
     */
    public void setDischargePort(String value) {
        setAttributeInternal(DISCHARGEPORT, value);
    }

    /**
     * Gets the attribute value for SHIP_PORT using the alias name ShipPort.
     * @return the SHIP_PORT
     */
    public String getShipPort() {
        return (String) getAttributeInternal(SHIPPORT);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIP_PORT using the alias name ShipPort.
     * @param value value to set the SHIP_PORT
     */
    public void setShipPort(String value) {
        setAttributeInternal(SHIPPORT, value);
    }

    /**
     * Gets the attribute value for HS_CODE using the alias name HsCode.
     * @return the HS_CODE
     */
    public String getHsCode() {
        return (String) getAttributeInternal(HSCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for HS_CODE using the alias name HsCode.
     * @param value value to set the HS_CODE
     */
    public void setHsCode(String value) {
        setAttributeInternal(HSCODE, value);
    }

    /**
     * Gets the attribute value for STANDARD_TRANSIT_TIME using the alias name StandardTransitTime.
     * @return the STANDARD_TRANSIT_TIME
     */
    public String getStandardTransitTime() {
        return (String) getAttributeInternal(STANDARDTRANSITTIME);
    }

    /**
     * Sets <code>value</code> as attribute value for STANDARD_TRANSIT_TIME using the alias name StandardTransitTime.
     * @param value value to set the STANDARD_TRANSIT_TIME
     */
    public void setStandardTransitTime(String value) {
        setAttributeInternal(STANDARDTRANSITTIME, value);
    }

    /**
     * Gets the attribute value for EX_MILL_DATE using the alias name ExMillDate.
     * @return the EX_MILL_DATE
     */
    public Date getExMillDate() {
        return (Date) getAttributeInternal(EXMILLDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for EX_MILL_DATE using the alias name ExMillDate.
     * @param value value to set the EX_MILL_DATE
     */
    public void setExMillDate(Date value) {
        setAttributeInternal(EXMILLDATE, value);
    }

    /**
     * Gets the attribute value for EX_COUNTRY_DATE using the alias name ExCountryDate.
     * @return the EX_COUNTRY_DATE
     */
    public Date getExCountryDate() {
        return (Date) getAttributeInternal(EXCOUNTRYDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for EX_COUNTRY_DATE using the alias name ExCountryDate.
     * @param value value to set the EX_COUNTRY_DATE
     */
    public void setExCountryDate(Date value) {
        setAttributeInternal(EXCOUNTRYDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @return the LAST_UPDATE_LOGIN
     */
    public Number getLastUpdateLogin() {
        return (Number) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin.
     * @param value value to set the LAST_UPDATE_LOGIN
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @return the LAST_UPDATE_DATE
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate.
     * @param value value to set the LAST_UPDATE_DATE
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @return the ATTRIBUTE1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1.
     * @param value value to set the ATTRIBUTE1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @return the ATTRIBUTE2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2.
     * @param value value to set the ATTRIBUTE2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @return the ATTRIBUTE3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3.
     * @param value value to set the ATTRIBUTE3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @return the ATTRIBUTE4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4.
     * @param value value to set the ATTRIBUTE4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @return the ATTRIBUTE5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5.
     * @param value value to set the ATTRIBUTE5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @return the ATTRIBUTE6
     */
    public String getAttribute6() {
        return (String) getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE6 using the alias name Attribute6.
     * @param value value to set the ATTRIBUTE6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @return the ATTRIBUTE7
     */
    public String getAttribute7() {
        return (String) getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE7 using the alias name Attribute7.
     * @param value value to set the ATTRIBUTE7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @return the ATTRIBUTE8
     */
    public String getAttribute8() {
        return (String) getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE8 using the alias name Attribute8.
     * @param value value to set the ATTRIBUTE8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @return the ATTRIBUTE9
     */
    public String getAttribute9() {
        return (String) getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE9 using the alias name Attribute9.
     * @param value value to set the ATTRIBUTE9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @return the ATTRIBUTE10
     */
    public String getAttribute10() {
        return (String) getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE10 using the alias name Attribute10.
     * @param value value to set the ATTRIBUTE10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @return the ATTRIBUTE11
     */
    public String getAttribute11() {
        return (String) getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE11 using the alias name Attribute11.
     * @param value value to set the ATTRIBUTE11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @return the ATTRIBUTE12
     */
    public String getAttribute12() {
        return (String) getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE12 using the alias name Attribute12.
     * @param value value to set the ATTRIBUTE12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @return the ATTRIBUTE13
     */
    public String getAttribute13() {
        return (String) getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE13 using the alias name Attribute13.
     * @param value value to set the ATTRIBUTE13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @return the ATTRIBUTE14
     */
    public String getAttribute14() {
        return (String) getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE14 using the alias name Attribute14.
     * @param value value to set the ATTRIBUTE14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @return the ATTRIBUTE15
     */
    public String getAttribute15() {
        return (String) getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE15 using the alias name Attribute15.
     * @param value value to set the ATTRIBUTE15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE16 using the alias name Attribute16.
     * @return the ATTRIBUTE16
     */
    public String getAttribute16() {
        return (String) getAttributeInternal(ATTRIBUTE16);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE16 using the alias name Attribute16.
     * @param value value to set the ATTRIBUTE16
     */
    public void setAttribute16(String value) {
        setAttributeInternal(ATTRIBUTE16, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE17 using the alias name Attribute17.
     * @return the ATTRIBUTE17
     */
    public String getAttribute17() {
        return (String) getAttributeInternal(ATTRIBUTE17);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE17 using the alias name Attribute17.
     * @param value value to set the ATTRIBUTE17
     */
    public void setAttribute17(String value) {
        setAttributeInternal(ATTRIBUTE17, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE18 using the alias name Attribute18.
     * @return the ATTRIBUTE18
     */
    public String getAttribute18() {
        return (String) getAttributeInternal(ATTRIBUTE18);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE18 using the alias name Attribute18.
     * @param value value to set the ATTRIBUTE18
     */
    public void setAttribute18(String value) {
        setAttributeInternal(ATTRIBUTE18, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE19 using the alias name Attribute19.
     * @return the ATTRIBUTE19
     */
    public String getAttribute19() {
        return (String) getAttributeInternal(ATTRIBUTE19);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE19 using the alias name Attribute19.
     * @param value value to set the ATTRIBUTE19
     */
    public void setAttribute19(String value) {
        setAttributeInternal(ATTRIBUTE19, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE20 using the alias name Attribute20.
     * @return the ATTRIBUTE20
     */
    public String getAttribute20() {
        return (String) getAttributeInternal(ATTRIBUTE20);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE20 using the alias name Attribute20.
     * @param value value to set the ATTRIBUTE20
     */
    public void setAttribute20(String value) {
        setAttributeInternal(ATTRIBUTE20, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE21 using the alias name Attribute21.
     * @return the ATTRIBUTE21
     */
    public String getAttribute21() {
        return (String) getAttributeInternal(ATTRIBUTE21);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE21 using the alias name Attribute21.
     * @param value value to set the ATTRIBUTE21
     */
    public void setAttribute21(String value) {
        setAttributeInternal(ATTRIBUTE21, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE22 using the alias name Attribute22.
     * @return the ATTRIBUTE22
     */
    public String getAttribute22() {
        return (String) getAttributeInternal(ATTRIBUTE22);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE22 using the alias name Attribute22.
     * @param value value to set the ATTRIBUTE22
     */
    public void setAttribute22(String value) {
        setAttributeInternal(ATTRIBUTE22, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE23 using the alias name Attribute23.
     * @return the ATTRIBUTE23
     */
    public String getAttribute23() {
        return (String) getAttributeInternal(ATTRIBUTE23);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE23 using the alias name Attribute23.
     * @param value value to set the ATTRIBUTE23
     */
    public void setAttribute23(String value) {
        setAttributeInternal(ATTRIBUTE23, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE24 using the alias name Attribute24.
     * @return the ATTRIBUTE24
     */
    public String getAttribute24() {
        return (String) getAttributeInternal(ATTRIBUTE24);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE24 using the alias name Attribute24.
     * @param value value to set the ATTRIBUTE24
     */
    public void setAttribute24(String value) {
        setAttributeInternal(ATTRIBUTE24, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE25 using the alias name Attribute25.
     * @return the ATTRIBUTE25
     */
    public String getAttribute25() {
        return (String) getAttributeInternal(ATTRIBUTE25);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE25 using the alias name Attribute25.
     * @param value value to set the ATTRIBUTE25
     */
    public void setAttribute25(String value) {
        setAttributeInternal(ATTRIBUTE25, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE26 using the alias name Attribute26.
     * @return the ATTRIBUTE26
     */
    public String getAttribute26() {
        return (String) getAttributeInternal(ATTRIBUTE26);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE26 using the alias name Attribute26.
     * @param value value to set the ATTRIBUTE26
     */
    public void setAttribute26(String value) {
        setAttributeInternal(ATTRIBUTE26, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE27 using the alias name Attribute27.
     * @return the ATTRIBUTE27
     */
    public String getAttribute27() {
        return (String) getAttributeInternal(ATTRIBUTE27);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE27 using the alias name Attribute27.
     * @param value value to set the ATTRIBUTE27
     */
    public void setAttribute27(String value) {
        setAttributeInternal(ATTRIBUTE27, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE28 using the alias name Attribute28.
     * @return the ATTRIBUTE28
     */
    public String getAttribute28() {
        return (String) getAttributeInternal(ATTRIBUTE28);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE28 using the alias name Attribute28.
     * @param value value to set the ATTRIBUTE28
     */
    public void setAttribute28(String value) {
        setAttributeInternal(ATTRIBUTE28, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE29 using the alias name Attribute29.
     * @return the ATTRIBUTE29
     */
    public String getAttribute29() {
        return (String) getAttributeInternal(ATTRIBUTE29);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE29 using the alias name Attribute29.
     * @param value value to set the ATTRIBUTE29
     */
    public void setAttribute29(String value) {
        setAttributeInternal(ATTRIBUTE29, value);
    }

    /**
     * Gets the attribute value for ATTRIBUTE30 using the alias name Attribute30.
     * @return the ATTRIBUTE30
     */
    public String getAttribute30() {
        return (String) getAttributeInternal(ATTRIBUTE30);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTRIBUTE30 using the alias name Attribute30.
     * @param value value to set the ATTRIBUTE30
     */
    public void setAttribute30(String value) {
        setAttributeInternal(ATTRIBUTE30, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OrgName.
     * @return the OrgName
     */
    public String getOrgName() {
        return (String) getAttributeInternal(ORGNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OrgName.
     * @param value value to set the  OrgName
     */
    public void setOrgName(String value) {
        setAttributeInternal(ORGNAME, value);
    }

    /**
     * Gets the attribute value for ORG_ID using the alias name OrgId.
     * @return the ORG_ID
     */
    public Number getOrgId() {
        return (Number) getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_ID using the alias name OrgId.
     * @param value value to set the ORG_ID
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for PI_DOC_NUMBER using the alias name PiDocNumber.
     * @return the PI_DOC_NUMBER
     */
    public Number getPiDocNumber() {
        return (Number) getAttributeInternal(PIDOCNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for PI_DOC_NUMBER using the alias name PiDocNumber.
     * @param value value to set the PI_DOC_NUMBER
     */
    public void setPiDocNumber(Number value) {
        setAttributeInternal(PIDOCNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Supplier.
     * @return the Supplier
     */
    public String getSupplier() {
        return (String) getAttributeInternal(SUPPLIER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Supplier.
     * @param value value to set the  Supplier
     */
    public void setSupplier(String value) {
        setAttributeInternal(SUPPLIER, value);
    }

    /**
     * Gets the attribute value for VERSION_DATE using the alias name VersionDate.
     * @return the VERSION_DATE
     */
    public Date getVersionDate() {
        return (Date) getAttributeInternal(VERSIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for VERSION_DATE using the alias name VersionDate.
     * @param value value to set the VERSION_DATE
     */
    public void setVersionDate(Date value) {
        setAttributeInternal(VERSIONDATE, value);
    }

    /**
     * Gets the attribute value for VERSION_NUMBER using the alias name VersionNumber.
     * @return the VERSION_NUMBER
     */
    public Number getVersionNumber() {
        return (Number) getAttributeInternal(VERSIONNUMBER);
    }

    /**
     * Sets <code>value</code> as attribute value for VERSION_NUMBER using the alias name VersionNumber.
     * @param value value to set the VERSION_NUMBER
     */
    public void setVersionNumber(Number value) {
        setAttributeInternal(VERSIONNUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreatedByName.
     * @return the CreatedByName
     */
    public String getCreatedByName() {
        return (String) getAttributeInternal(CREATEDBYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreatedByName.
     * @param value value to set the  CreatedByName
     */
    public void setCreatedByName(String value) {
        setAttributeInternal(CREATEDBYNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ReceivingDelay.
     * @return the ReceivingDelay
     */
    public Number getReceivingDelay() {
        return (Number) getAttributeInternal(RECEIVINGDELAY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ReceivingDelay.
     * @param value value to set the  ReceivingDelay
     */
    public void setReceivingDelay(Number value) {
        setAttributeInternal(RECEIVINGDELAY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LcEnteringDate.
     * @return the LcEnteringDate
     */
    public Date getLcEnteringDate() {
        return (Date) getAttributeInternal(LCENTERINGDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LcEnteringDate.
     * @param value value to set the  LcEnteringDate
     */
    public void setLcEnteringDate(Date value) {
        setAttributeInternal(LCENTERINGDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LcEnteringDealy.
     * @return the LcEnteringDealy
     */
    public Number getLcEnteringDealy() {
        return (Number) getAttributeInternal(LCENTERINGDEALY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LcEnteringDealy.
     * @param value value to set the  LcEnteringDealy
     */
    public void setLcEnteringDealy(Number value) {
        setAttributeInternal(LCENTERINGDEALY, value);
    }

    /**
     * Gets the attribute value for DELIVERY_DATE using the alias name DeliveryDate.
     * @return the DELIVERY_DATE
     */
    public Date getDeliveryDate() {
        return (Date) getAttributeInternal(DELIVERYDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for DELIVERY_DATE using the alias name DeliveryDate.
     * @param value value to set the DELIVERY_DATE
     */
    public void setDeliveryDate(Date value) {
        setAttributeInternal(DELIVERYDATE, value);
    }

    /**
     * Gets the attribute value for RECEIVED_DATE using the alias name ReceivedDate.
     * @return the RECEIVED_DATE
     */
    public Date getReceivedDate() {
        return (Date) getAttributeInternal(RECEIVEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for RECEIVED_DATE using the alias name ReceivedDate.
     * @param value value to set the RECEIVED_DATE
     */
    public void setReceivedDate(Date value) {
        setAttributeInternal(RECEIVEDDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RecieveDelay.
     * @return the RecieveDelay
     */
  

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ImpPiDetails.
     */
    public RowIterator getImpPiDetails() {
        return (RowIterator)getAttributeInternal(IMPPIDETAILS);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ImpPiAdjustments.
     */
    public RowIterator getImpPiAdjustments() {
        return (RowIterator)getAttributeInternal(IMPPIADJUSTMENTS);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ItemQtyDetail.
     */
    public RowIterator getItemQtyDetail() {
        return (RowIterator)getAttributeInternal(ITEMQTYDETAIL);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link FillBPO.
     */
    public RowIterator getFillBPO() {
        return (RowIterator)getAttributeInternal(FILLBPO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SuppVO1.
     */
    public RowSet getSuppVO1() {
        return (RowSet)getAttributeInternal(SUPPVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CustomerVO1.
     */
    public RowSet getCustomerVO1() {
        return (RowSet)getAttributeInternal(CUSTOMERVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> SupplierVO1.
     */
    public RowSet getSupplierVO1() {
        return (RowSet)getAttributeInternal(SUPPLIERVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CurrencyVO1.
     */
    public RowSet getCurrencyVO1() {
        return (RowSet)getAttributeInternal(CURRENCYVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> OrgVO1.
     */
    public RowSet getOrgVO1() {
        return (RowSet)getAttributeInternal(ORGVO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
