package mnj.ont.model.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 26 15:00:05 BDT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ImpPiLinesVOExImpl extends ImpPiLinesVOImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ImpPiLinesVOExImpl() {
    }
}
