package mnj.ont.model.views;

import mnj.ont.model.entities.ImpPiLinesEOImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 26 15:00:05 BDT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ImpPiLinesVOExRowImpl extends ImpPiLinesVORowImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ImpPiLinesVOExRowImpl() {
    }

    /**
     * Gets ImpPiLinesEO entity object.
     * @return the ImpPiLinesEO
     */
    public ImpPiLinesEOImpl getImpPiLinesEO() {
        return (ImpPiLinesEOImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for the calculated attribute BblcNo.
     * @return the BblcNo
     */
    public String getBblcNo() {
        return super.getBblcNo();
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BblcNo.
     * @param value value to set the  BblcNo
     */
    public void setBblcNo(String value) {
        super.setBblcNo(value);
    }

    /**
     * Gets the attribute value for the calculated attribute SpoNos.
     * @return the SpoNos
     */
    public String getSpoNos() {
        return super.getSpoNos();
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SpoNos.
     * @param value value to set the  SpoNos
     */
    public void setSpoNos(String value) {
        super.setSpoNos(value);
    }

    /**
     * Gets the attribute value for the calculated attribute SpoBuyer.
     * @return the SpoBuyer
     */
    public String getSpoBuyer() {
        return super.getSpoBuyer();
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SpoBuyer.
     * @param value value to set the  SpoBuyer
     */
    public void setSpoBuyer(String value) {
        super.setSpoBuyer(value);
    }

    /**
     * Gets the attribute value for the calculated attribute SpoSeason.
     * @return the SpoSeason
     */
    public String getSpoSeason() {
        return super.getSpoSeason();
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SpoSeason.
     * @param value value to set the  SpoSeason
     */
    public void setSpoSeason(String value) {
        super.setSpoSeason(value);
    }

    /**
     * Gets the attribute value for the calculated attribute OrgName.
     * @return the OrgName
     */
    public String getOrgName() {
        return super.getOrgName();
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OrgName.
     * @param value value to set the  OrgName
     */
    public void setOrgName(String value) {
        super.setOrgName(value);
    }

    /**
     * Gets the attribute value for the calculated attribute Supplier.
     * @return the Supplier
     */
    public String getSupplier() {
        return super.getSupplier();
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Supplier.
     * @param value value to set the  Supplier
     */
    public void setSupplier(String value) {
        super.setSupplier(value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreatedByName.
     * @return the CreatedByName
     */
    public String getCreatedByName() {
        return super.getCreatedByName();
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreatedByName.
     * @param value value to set the  CreatedByName
     */
    public void setCreatedByName(String value) {
        super.setCreatedByName(value);
    }

    /**
     * Gets the attribute value for the calculated attribute ReceivingDelay.
     * @return the ReceivingDelay
     */
    public Number getReceivingDelay() {
        return super.getReceivingDelay();
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ReceivingDelay.
     * @param value value to set the  ReceivingDelay
     */
    public void setReceivingDelay(Number value) {
        super.setReceivingDelay(value);
    }

    /**
     * Gets the attribute value for the calculated attribute LcEnteringDate.
     * @return the LcEnteringDate
     */
    public Date getLcEnteringDate() {
        return super.getLcEnteringDate();
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LcEnteringDate.
     * @param value value to set the  LcEnteringDate
     */
    public void setLcEnteringDate(Date value) {
        super.setLcEnteringDate(value);
    }

    /**
     * Gets the attribute value for the calculated attribute LcEnteringDealy.
     * @return the LcEnteringDealy
     */
    public Number getLcEnteringDealy() {
        return super.getLcEnteringDealy();
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LcEnteringDealy.
     * @param value value to set the  LcEnteringDealy
     */
    public void setLcEnteringDealy(Number value) {
        super.setLcEnteringDealy(value);
    }
}
