package mnj.ont.model.entities;

import java.sql.SQLException;

import java.util.Map;

import oracle.adf.share.ADFContext;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Jan 30 13:34:47 BDT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ImpPiLinesEOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        ImpPiLineId {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getImpPiLineId();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setImpPiLineId((Number)value);
            }
        }
        ,
        ImpPiHeaderId {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getImpPiHeaderId();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setImpPiHeaderId((Number)value);
            }
        }
        ,
        PiNo {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getPiNo();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setPiNo((String)value);
            }
        }
        ,
        PiDate {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getPiDate();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setPiDate((Date)value);
            }
        }
        ,
        Currency {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getCurrency();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setCurrency((String)value);
            }
        }
        ,
        TotalValue {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getTotalValue();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setTotalValue((Number)value);
            }
        }
        ,
        EstimatedShipDate {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getEstimatedShipDate();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setEstimatedShipDate((Date)value);
            }
        }
        ,
        PaymentTerm {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getPaymentTerm();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setPaymentTerm((String)value);
            }
        }
        ,
        SupplierId {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getSupplierId();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setSupplierId((Number)value);
            }
        }
        ,
        DischargePort {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getDischargePort();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setDischargePort((String)value);
            }
        }
        ,
        ShipPort {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getShipPort();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setShipPort((String)value);
            }
        }
        ,
        HsCode {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getHsCode();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setHsCode((String)value);
            }
        }
        ,
        StandardTransitTime {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getStandardTransitTime();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setStandardTransitTime((String)value);
            }
        }
        ,
        ExMillDate {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getExMillDate();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setExMillDate((Date)value);
            }
        }
        ,
        ExCountryDate {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getExCountryDate();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setExCountryDate((Date)value);
            }
        }
        ,
        LastUpdateLogin {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getLastUpdateLogin();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setLastUpdateLogin((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getCreationDate();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        Attribute1 {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getAttribute1();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        Attribute2 {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getAttribute2();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setAttribute2((String)value);
            }
        }
        ,
        Attribute3 {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getAttribute3();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setAttribute3((String)value);
            }
        }
        ,
        Attribute4 {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getAttribute4();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setAttribute4((String)value);
            }
        }
        ,
        Attribute5 {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getAttribute5();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setAttribute5((String)value);
            }
        }
        ,
        Attribute6 {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getAttribute6();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setAttribute6((String)value);
            }
        }
        ,
        Attribute7 {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getAttribute7();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setAttribute7((String)value);
            }
        }
        ,
        Attribute8 {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getAttribute8();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setAttribute8((String)value);
            }
        }
        ,
        Attribute9 {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getAttribute9();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setAttribute9((String)value);
            }
        }
        ,
        Attribute10 {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getAttribute10();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setAttribute10((String)value);
            }
        }
        ,
        Attribute11 {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getAttribute11();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setAttribute11((String)value);
            }
        }
        ,
        Attribute12 {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getAttribute12();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setAttribute12((String)value);
            }
        }
        ,
        Attribute13 {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getAttribute13();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setAttribute13((String)value);
            }
        }
        ,
        Attribute14 {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getAttribute14();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setAttribute14((String)value);
            }
        }
        ,
        Attribute15 {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getAttribute15();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setAttribute15((String)value);
            }
        }
        ,
        Attribute16 {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getAttribute16();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setAttribute16((String)value);
            }
        }
        ,
        Attribute17 {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getAttribute17();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setAttribute17((String)value);
            }
        }
        ,
        Attribute18 {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getAttribute18();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setAttribute18((String)value);
            }
        }
        ,
        Attribute19 {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getAttribute19();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setAttribute19((String)value);
            }
        }
        ,
        Attribute20 {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getAttribute20();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setAttribute20((String)value);
            }
        }
        ,
        Attribute21 {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getAttribute21();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setAttribute21((String)value);
            }
        }
        ,
        Attribute22 {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getAttribute22();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setAttribute22((String)value);
            }
        }
        ,
        Attribute23 {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getAttribute23();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setAttribute23((String)value);
            }
        }
        ,
        Attribute24 {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getAttribute24();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setAttribute24((String)value);
            }
        }
        ,
        Attribute25 {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getAttribute25();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setAttribute25((String)value);
            }
        }
        ,
        Attribute26 {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getAttribute26();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setAttribute26((String)value);
            }
        }
        ,
        Attribute27 {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getAttribute27();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setAttribute27((String)value);
            }
        }
        ,
        Attribute28 {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getAttribute28();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setAttribute28((String)value);
            }
        }
        ,
        Attribute29 {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getAttribute29();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setAttribute29((String)value);
            }
        }
        ,
        Attribute30 {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getAttribute30();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setAttribute30((String)value);
            }
        }
        ,
        PiDocNumber {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getPiDocNumber();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setPiDocNumber((Number)value);
            }
        }
        ,
        OrgId {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getOrgId();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        VersionNumber {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getVersionNumber();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setVersionNumber((Number)value);
            }
        }
        ,
        VersionDate {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getVersionDate();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setVersionDate((Date)value);
            }
        }
        ,
        DeliveryDate {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getDeliveryDate();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setDeliveryDate((Date)value);
            }
        }
        ,
        ReceivedDate {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getReceivedDate();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setReceivedDate((Date)value);
            }
        }
        ,
        ImpPiDetails {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getImpPiDetails();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ImpPiAdjustments {
            public Object get(ImpPiLinesEOImpl obj) {
                return obj.getImpPiAdjustments();
            }

            public void put(ImpPiLinesEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(ImpPiLinesEOImpl object);

        public abstract void put(ImpPiLinesEOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int IMPPILINEID = AttributesEnum.ImpPiLineId.index();
    public static final int IMPPIHEADERID = AttributesEnum.ImpPiHeaderId.index();
    public static final int PINO = AttributesEnum.PiNo.index();
    public static final int PIDATE = AttributesEnum.PiDate.index();
    public static final int CURRENCY = AttributesEnum.Currency.index();
    public static final int TOTALVALUE = AttributesEnum.TotalValue.index();
    public static final int ESTIMATEDSHIPDATE = AttributesEnum.EstimatedShipDate.index();
    public static final int PAYMENTTERM = AttributesEnum.PaymentTerm.index();
    public static final int SUPPLIERID = AttributesEnum.SupplierId.index();
    public static final int DISCHARGEPORT = AttributesEnum.DischargePort.index();
    public static final int SHIPPORT = AttributesEnum.ShipPort.index();
    public static final int HSCODE = AttributesEnum.HsCode.index();
    public static final int STANDARDTRANSITTIME = AttributesEnum.StandardTransitTime.index();
    public static final int EXMILLDATE = AttributesEnum.ExMillDate.index();
    public static final int EXCOUNTRYDATE = AttributesEnum.ExCountryDate.index();
    public static final int LASTUPDATELOGIN = AttributesEnum.LastUpdateLogin.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int ATTRIBUTE2 = AttributesEnum.Attribute2.index();
    public static final int ATTRIBUTE3 = AttributesEnum.Attribute3.index();
    public static final int ATTRIBUTE4 = AttributesEnum.Attribute4.index();
    public static final int ATTRIBUTE5 = AttributesEnum.Attribute5.index();
    public static final int ATTRIBUTE6 = AttributesEnum.Attribute6.index();
    public static final int ATTRIBUTE7 = AttributesEnum.Attribute7.index();
    public static final int ATTRIBUTE8 = AttributesEnum.Attribute8.index();
    public static final int ATTRIBUTE9 = AttributesEnum.Attribute9.index();
    public static final int ATTRIBUTE10 = AttributesEnum.Attribute10.index();
    public static final int ATTRIBUTE11 = AttributesEnum.Attribute11.index();
    public static final int ATTRIBUTE12 = AttributesEnum.Attribute12.index();
    public static final int ATTRIBUTE13 = AttributesEnum.Attribute13.index();
    public static final int ATTRIBUTE14 = AttributesEnum.Attribute14.index();
    public static final int ATTRIBUTE15 = AttributesEnum.Attribute15.index();
    public static final int ATTRIBUTE16 = AttributesEnum.Attribute16.index();
    public static final int ATTRIBUTE17 = AttributesEnum.Attribute17.index();
    public static final int ATTRIBUTE18 = AttributesEnum.Attribute18.index();
    public static final int ATTRIBUTE19 = AttributesEnum.Attribute19.index();
    public static final int ATTRIBUTE20 = AttributesEnum.Attribute20.index();
    public static final int ATTRIBUTE21 = AttributesEnum.Attribute21.index();
    public static final int ATTRIBUTE22 = AttributesEnum.Attribute22.index();
    public static final int ATTRIBUTE23 = AttributesEnum.Attribute23.index();
    public static final int ATTRIBUTE24 = AttributesEnum.Attribute24.index();
    public static final int ATTRIBUTE25 = AttributesEnum.Attribute25.index();
    public static final int ATTRIBUTE26 = AttributesEnum.Attribute26.index();
    public static final int ATTRIBUTE27 = AttributesEnum.Attribute27.index();
    public static final int ATTRIBUTE28 = AttributesEnum.Attribute28.index();
    public static final int ATTRIBUTE29 = AttributesEnum.Attribute29.index();
    public static final int ATTRIBUTE30 = AttributesEnum.Attribute30.index();
    public static final int PIDOCNUMBER = AttributesEnum.PiDocNumber.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int VERSIONNUMBER = AttributesEnum.VersionNumber.index();
    public static final int VERSIONDATE = AttributesEnum.VersionDate.index();
    public static final int DELIVERYDATE = AttributesEnum.DeliveryDate.index();
    public static final int RECEIVEDDATE = AttributesEnum.ReceivedDate.index();
    public static final int IMPPIDETAILS = AttributesEnum.ImpPiDetails.index();
    public static final int IMPPIADJUSTMENTS = AttributesEnum.ImpPiAdjustments.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ImpPiLinesEOImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("mnj.ont.model.entities.ImpPiLinesEO");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for ImpPiLineId, using the alias name ImpPiLineId.
     * @return the ImpPiLineId
     */
    public Number getImpPiLineId() {
        return (Number)getAttributeInternal(IMPPILINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ImpPiLineId.
     * @param value value to set the ImpPiLineId
     */
    public void setImpPiLineId(Number value) {
        setAttributeInternal(IMPPILINEID, value);
    }

    /**
     * Gets the attribute value for ImpPiHeaderId, using the alias name ImpPiHeaderId.
     * @return the ImpPiHeaderId
     */
    public Number getImpPiHeaderId() {
        return (Number)getAttributeInternal(IMPPIHEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ImpPiHeaderId.
     * @param value value to set the ImpPiHeaderId
     */
    public void setImpPiHeaderId(Number value) {
        setAttributeInternal(IMPPIHEADERID, value);
    }

    /**
     * Gets the attribute value for PiNo, using the alias name PiNo.
     * @return the PiNo
     */
    public String getPiNo() {
        return (String)getAttributeInternal(PINO);
    }

    /**
     * Sets <code>value</code> as the attribute value for PiNo.
     * @param value value to set the PiNo
     */
    public void setPiNo(String value) {
        setAttributeInternal(PINO, value);
    }

    /**
     * Gets the attribute value for PiDate, using the alias name PiDate.
     * @return the PiDate
     */
    public Date getPiDate() {
        return (Date)getAttributeInternal(PIDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for PiDate.
     * @param value value to set the PiDate
     */
    public void setPiDate(Date value) {
        setAttributeInternal(PIDATE, value);
    }

    /**
     * Gets the attribute value for Currency, using the alias name Currency.
     * @return the Currency
     */
    public String getCurrency() {
        return (String)getAttributeInternal(CURRENCY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Currency.
     * @param value value to set the Currency
     */
    public void setCurrency(String value) {
        setAttributeInternal(CURRENCY, value);
    }

    /**
     * Gets the attribute value for TotalValue, using the alias name TotalValue.
     * @return the TotalValue
     */
    public Number getTotalValue() {
        return (Number)getAttributeInternal(TOTALVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TotalValue.
     * @param value value to set the TotalValue
     */
    public void setTotalValue(Number value) {
        setAttributeInternal(TOTALVALUE, value);
    }

    /**
     * Gets the attribute value for EstimatedShipDate, using the alias name EstimatedShipDate.
     * @return the EstimatedShipDate
     */
    public Date getEstimatedShipDate() {
        return (Date)getAttributeInternal(ESTIMATEDSHIPDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for EstimatedShipDate.
     * @param value value to set the EstimatedShipDate
     */
    public void setEstimatedShipDate(Date value) {
        setAttributeInternal(ESTIMATEDSHIPDATE, value);
    }

    /**
     * Gets the attribute value for PaymentTerm, using the alias name PaymentTerm.
     * @return the PaymentTerm
     */
    public String getPaymentTerm() {
        return (String)getAttributeInternal(PAYMENTTERM);
    }

    /**
     * Sets <code>value</code> as the attribute value for PaymentTerm.
     * @param value value to set the PaymentTerm
     */
    public void setPaymentTerm(String value) {
        setAttributeInternal(PAYMENTTERM, value);
    }

    /**
     * Gets the attribute value for SupplierId, using the alias name SupplierId.
     * @return the SupplierId
     */
    public Number getSupplierId() {
        return (Number)getAttributeInternal(SUPPLIERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for SupplierId.
     * @param value value to set the SupplierId
     */
    public void setSupplierId(Number value) {
        setAttributeInternal(SUPPLIERID, value);
    }

    /**
     * Gets the attribute value for DischargePort, using the alias name DischargePort.
     * @return the DischargePort
     */
    public String getDischargePort() {
        return (String)getAttributeInternal(DISCHARGEPORT);
    }

    /**
     * Sets <code>value</code> as the attribute value for DischargePort.
     * @param value value to set the DischargePort
     */
    public void setDischargePort(String value) {
        setAttributeInternal(DISCHARGEPORT, value);
    }

    /**
     * Gets the attribute value for ShipPort, using the alias name ShipPort.
     * @return the ShipPort
     */
    public String getShipPort() {
        return (String)getAttributeInternal(SHIPPORT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ShipPort.
     * @param value value to set the ShipPort
     */
    public void setShipPort(String value) {
        setAttributeInternal(SHIPPORT, value);
    }

    /**
     * Gets the attribute value for HsCode, using the alias name HsCode.
     * @return the HsCode
     */
    public String getHsCode() {
        return (String)getAttributeInternal(HSCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for HsCode.
     * @param value value to set the HsCode
     */
    public void setHsCode(String value) {
        setAttributeInternal(HSCODE, value);
    }

    /**
     * Gets the attribute value for StandardTransitTime, using the alias name StandardTransitTime.
     * @return the StandardTransitTime
     */
    public String getStandardTransitTime() {
        return (String)getAttributeInternal(STANDARDTRANSITTIME);
    }

    /**
     * Sets <code>value</code> as the attribute value for StandardTransitTime.
     * @param value value to set the StandardTransitTime
     */
    public void setStandardTransitTime(String value) {
        setAttributeInternal(STANDARDTRANSITTIME, value);
    }

    /**
     * Gets the attribute value for ExMillDate, using the alias name ExMillDate.
     * @return the ExMillDate
     */
    public Date getExMillDate() {
        return (Date)getAttributeInternal(EXMILLDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExMillDate.
     * @param value value to set the ExMillDate
     */
    public void setExMillDate(Date value) {
        setAttributeInternal(EXMILLDATE, value);
    }

    /**
     * Gets the attribute value for ExCountryDate, using the alias name ExCountryDate.
     * @return the ExCountryDate
     */
    public Date getExCountryDate() {
        return (Date)getAttributeInternal(EXCOUNTRYDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExCountryDate.
     * @param value value to set the ExCountryDate
     */
    public void setExCountryDate(Date value) {
        setAttributeInternal(EXCOUNTRYDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin.
     * @return the LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateLogin.
     * @param value value to set the LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CreationDate, using the alias name CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreationDate.
     * @param value value to set the CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for Attribute1, using the alias name Attribute1.
     * @return the Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute1.
     * @param value value to set the Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for Attribute2, using the alias name Attribute2.
     * @return the Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute2.
     * @param value value to set the Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**
     * Gets the attribute value for Attribute3, using the alias name Attribute3.
     * @return the Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute3.
     * @param value value to set the Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**
     * Gets the attribute value for Attribute4, using the alias name Attribute4.
     * @return the Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute4.
     * @param value value to set the Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**
     * Gets the attribute value for Attribute5, using the alias name Attribute5.
     * @return the Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute5.
     * @param value value to set the Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**
     * Gets the attribute value for Attribute6, using the alias name Attribute6.
     * @return the Attribute6
     */
    public String getAttribute6() {
        return (String)getAttributeInternal(ATTRIBUTE6);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute6.
     * @param value value to set the Attribute6
     */
    public void setAttribute6(String value) {
        setAttributeInternal(ATTRIBUTE6, value);
    }

    /**
     * Gets the attribute value for Attribute7, using the alias name Attribute7.
     * @return the Attribute7
     */
    public String getAttribute7() {
        return (String)getAttributeInternal(ATTRIBUTE7);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute7.
     * @param value value to set the Attribute7
     */
    public void setAttribute7(String value) {
        setAttributeInternal(ATTRIBUTE7, value);
    }

    /**
     * Gets the attribute value for Attribute8, using the alias name Attribute8.
     * @return the Attribute8
     */
    public String getAttribute8() {
        return (String)getAttributeInternal(ATTRIBUTE8);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute8.
     * @param value value to set the Attribute8
     */
    public void setAttribute8(String value) {
        setAttributeInternal(ATTRIBUTE8, value);
    }

    /**
     * Gets the attribute value for Attribute9, using the alias name Attribute9.
     * @return the Attribute9
     */
    public String getAttribute9() {
        return (String)getAttributeInternal(ATTRIBUTE9);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute9.
     * @param value value to set the Attribute9
     */
    public void setAttribute9(String value) {
        setAttributeInternal(ATTRIBUTE9, value);
    }

    /**
     * Gets the attribute value for Attribute10, using the alias name Attribute10.
     * @return the Attribute10
     */
    public String getAttribute10() {
        return (String)getAttributeInternal(ATTRIBUTE10);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute10.
     * @param value value to set the Attribute10
     */
    public void setAttribute10(String value) {
        setAttributeInternal(ATTRIBUTE10, value);
    }

    /**
     * Gets the attribute value for Attribute11, using the alias name Attribute11.
     * @return the Attribute11
     */
    public String getAttribute11() {
        return (String)getAttributeInternal(ATTRIBUTE11);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute11.
     * @param value value to set the Attribute11
     */
    public void setAttribute11(String value) {
        setAttributeInternal(ATTRIBUTE11, value);
    }

    /**
     * Gets the attribute value for Attribute12, using the alias name Attribute12.
     * @return the Attribute12
     */
    public String getAttribute12() {
        return (String)getAttributeInternal(ATTRIBUTE12);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute12.
     * @param value value to set the Attribute12
     */
    public void setAttribute12(String value) {
        setAttributeInternal(ATTRIBUTE12, value);
    }

    /**
     * Gets the attribute value for Attribute13, using the alias name Attribute13.
     * @return the Attribute13
     */
    public String getAttribute13() {
        return (String)getAttributeInternal(ATTRIBUTE13);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute13.
     * @param value value to set the Attribute13
     */
    public void setAttribute13(String value) {
        setAttributeInternal(ATTRIBUTE13, value);
    }

    /**
     * Gets the attribute value for Attribute14, using the alias name Attribute14.
     * @return the Attribute14
     */
    public String getAttribute14() {
        return (String)getAttributeInternal(ATTRIBUTE14);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute14.
     * @param value value to set the Attribute14
     */
    public void setAttribute14(String value) {
        setAttributeInternal(ATTRIBUTE14, value);
    }

    /**
     * Gets the attribute value for Attribute15, using the alias name Attribute15.
     * @return the Attribute15
     */
    public String getAttribute15() {
        return (String)getAttributeInternal(ATTRIBUTE15);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute15.
     * @param value value to set the Attribute15
     */
    public void setAttribute15(String value) {
        setAttributeInternal(ATTRIBUTE15, value);
    }

    /**
     * Gets the attribute value for Attribute16, using the alias name Attribute16.
     * @return the Attribute16
     */
    public String getAttribute16() {
        return (String)getAttributeInternal(ATTRIBUTE16);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute16.
     * @param value value to set the Attribute16
     */
    public void setAttribute16(String value) {
        setAttributeInternal(ATTRIBUTE16, value);
    }

    /**
     * Gets the attribute value for Attribute17, using the alias name Attribute17.
     * @return the Attribute17
     */
    public String getAttribute17() {
        return (String)getAttributeInternal(ATTRIBUTE17);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute17.
     * @param value value to set the Attribute17
     */
    public void setAttribute17(String value) {
        setAttributeInternal(ATTRIBUTE17, value);
    }

    /**
     * Gets the attribute value for Attribute18, using the alias name Attribute18.
     * @return the Attribute18
     */
    public String getAttribute18() {
        return (String)getAttributeInternal(ATTRIBUTE18);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute18.
     * @param value value to set the Attribute18
     */
    public void setAttribute18(String value) {
        setAttributeInternal(ATTRIBUTE18, value);
    }

    /**
     * Gets the attribute value for Attribute19, using the alias name Attribute19.
     * @return the Attribute19
     */
    public String getAttribute19() {
        return (String)getAttributeInternal(ATTRIBUTE19);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute19.
     * @param value value to set the Attribute19
     */
    public void setAttribute19(String value) {
        setAttributeInternal(ATTRIBUTE19, value);
    }

    /**
     * Gets the attribute value for Attribute20, using the alias name Attribute20.
     * @return the Attribute20
     */
    public String getAttribute20() {
        return (String)getAttributeInternal(ATTRIBUTE20);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute20.
     * @param value value to set the Attribute20
     */
    public void setAttribute20(String value) {
        setAttributeInternal(ATTRIBUTE20, value);
    }

    /**
     * Gets the attribute value for Attribute21, using the alias name Attribute21.
     * @return the Attribute21
     */
    public String getAttribute21() {
        return (String)getAttributeInternal(ATTRIBUTE21);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute21.
     * @param value value to set the Attribute21
     */
    public void setAttribute21(String value) {
        setAttributeInternal(ATTRIBUTE21, value);
    }

    /**
     * Gets the attribute value for Attribute22, using the alias name Attribute22.
     * @return the Attribute22
     */
    public String getAttribute22() {
        return (String)getAttributeInternal(ATTRIBUTE22);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute22.
     * @param value value to set the Attribute22
     */
    public void setAttribute22(String value) {
        setAttributeInternal(ATTRIBUTE22, value);
    }

    /**
     * Gets the attribute value for Attribute23, using the alias name Attribute23.
     * @return the Attribute23
     */
    public String getAttribute23() {
        return (String)getAttributeInternal(ATTRIBUTE23);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute23.
     * @param value value to set the Attribute23
     */
    public void setAttribute23(String value) {
        setAttributeInternal(ATTRIBUTE23, value);
    }

    /**
     * Gets the attribute value for Attribute24, using the alias name Attribute24.
     * @return the Attribute24
     */
    public String getAttribute24() {
        return (String)getAttributeInternal(ATTRIBUTE24);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute24.
     * @param value value to set the Attribute24
     */
    public void setAttribute24(String value) {
        setAttributeInternal(ATTRIBUTE24, value);
    }

    /**
     * Gets the attribute value for Attribute25, using the alias name Attribute25.
     * @return the Attribute25
     */
    public String getAttribute25() {
        return (String)getAttributeInternal(ATTRIBUTE25);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute25.
     * @param value value to set the Attribute25
     */
    public void setAttribute25(String value) {
        setAttributeInternal(ATTRIBUTE25, value);
    }

    /**
     * Gets the attribute value for Attribute26, using the alias name Attribute26.
     * @return the Attribute26
     */
    public String getAttribute26() {
        return (String)getAttributeInternal(ATTRIBUTE26);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute26.
     * @param value value to set the Attribute26
     */
    public void setAttribute26(String value) {
        setAttributeInternal(ATTRIBUTE26, value);
    }

    /**
     * Gets the attribute value for Attribute27, using the alias name Attribute27.
     * @return the Attribute27
     */
    public String getAttribute27() {
        return (String)getAttributeInternal(ATTRIBUTE27);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute27.
     * @param value value to set the Attribute27
     */
    public void setAttribute27(String value) {
        setAttributeInternal(ATTRIBUTE27, value);
    }

    /**
     * Gets the attribute value for Attribute28, using the alias name Attribute28.
     * @return the Attribute28
     */
    public String getAttribute28() {
        return (String)getAttributeInternal(ATTRIBUTE28);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute28.
     * @param value value to set the Attribute28
     */
    public void setAttribute28(String value) {
        setAttributeInternal(ATTRIBUTE28, value);
    }

    /**
     * Gets the attribute value for Attribute29, using the alias name Attribute29.
     * @return the Attribute29
     */
    public String getAttribute29() {
        return (String)getAttributeInternal(ATTRIBUTE29);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute29.
     * @param value value to set the Attribute29
     */
    public void setAttribute29(String value) {
        setAttributeInternal(ATTRIBUTE29, value);
    }

    /**
     * Gets the attribute value for Attribute30, using the alias name Attribute30.
     * @return the Attribute30
     */
    public String getAttribute30() {
        return (String)getAttributeInternal(ATTRIBUTE30);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attribute30.
     * @param value value to set the Attribute30
     */
    public void setAttribute30(String value) {
        setAttributeInternal(ATTRIBUTE30, value);
    }

    /**
     * Gets the attribute value for PiDocNumber, using the alias name PiDocNumber.
     * @return the PiDocNumber
     */
    public Number getPiDocNumber() {
        return (Number)getAttributeInternal(PIDOCNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for PiDocNumber.
     * @param value value to set the PiDocNumber
     */
    public void setPiDocNumber(Number value) {
        setAttributeInternal(PIDOCNUMBER, value);
    }

    /**
     * Gets the attribute value for OrgId, using the alias name OrgId.
     * @return the OrgId
     */
    public Number getOrgId() {
        return (Number)getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrgId.
     * @param value value to set the OrgId
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for VersionNumber, using the alias name VersionNumber.
     * @return the VersionNumber
     */
    public Number getVersionNumber() {
        return (Number)getAttributeInternal(VERSIONNUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for VersionNumber.
     * @param value value to set the VersionNumber
     */
    public void setVersionNumber(Number value) {
        setAttributeInternal(VERSIONNUMBER, value);
    }

    /**
     * Gets the attribute value for VersionDate, using the alias name VersionDate.
     * @return the VersionDate
     */
    public Date getVersionDate() {
        return (Date)getAttributeInternal(VERSIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for VersionDate.
     * @param value value to set the VersionDate
     */
    public void setVersionDate(Date value) {
        setAttributeInternal(VERSIONDATE, value);
    }

    /**
     * Gets the attribute value for DeliveryDate, using the alias name DeliveryDate.
     * @return the DeliveryDate
     */
    public Date getDeliveryDate() {
        return (Date)getAttributeInternal(DELIVERYDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DeliveryDate.
     * @param value value to set the DeliveryDate
     */
    public void setDeliveryDate(Date value) {
        setAttributeInternal(DELIVERYDATE, value);
    }

    /**
     * Gets the attribute value for ReceivedDate, using the alias name ReceivedDate.
     * @return the ReceivedDate
     */
    public Date getReceivedDate() {
        return (Date)getAttributeInternal(RECEIVEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReceivedDate.
     * @param value value to set the ReceivedDate
     */
    public void setReceivedDate(Date value) {
        setAttributeInternal(RECEIVEDDATE, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getImpPiDetails() {
        return (RowIterator)getAttributeInternal(IMPPIDETAILS);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getImpPiAdjustments() {
        return (RowIterator)getAttributeInternal(IMPPIADJUSTMENTS);
    }


    /**
     * @param impPiLineId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number impPiLineId) {
        return new Key(new Object[]{impPiLineId});
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
     protected void create(AttributeList attributeList) {
         super.create(attributeList);
         /* Sequence Generation Code of Header by PwC */  
         oracle.jbo.server.SequenceImpl s = new oracle.jbo.server.SequenceImpl("IEDOC_IMP_PI_LINES_S",getDBTransaction());          
         oracle.jbo.domain.Number sVal = s.getSequenceNumber();          
         setImpPiLineId(sVal);
         /* End Sequence Generation Code of Header by PwC */
     }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
     public int getSrNoString() {
           int srno = 0;
           String stmt = "BEGIN :1 := IEDOC_DOC_NO_PKG.IMPORT_PI_DOC; end;";
           java.sql.CallableStatement cs =   getDBTransaction().createCallableStatement(stmt, 1);
           try {
               cs.registerOutParameter(1, oracle.jdbc.OracleTypes.NUMBER);
               cs.execute();
               srno = cs.getInt(1);
               cs.close();
           } catch (Exception e) {
               e.printStackTrace();
           }
           return srno;
       } 
     
     /**
      * Custom DML update/insert/delete logic here.
      * @param operation the operation type
      * @param e the transaction event
      */
     protected void doDML(int operation, TransactionEvent e) {
         Map sessionScope = ADFContext.getCurrent().getSessionScope();   
         String user = (String)sessionScope.get("userId");
         System.out.println("Document No -->"+getSrNoString());
         if(DML_UPDATE == operation){
             try {
                 setLastUpdateDate((Date)Date.getCurrentDate()); 
                 setLastUpdatedBy(new oracle.jbo.domain.Number(user));
             } catch (SQLException f) {
                 System.out.println(f.getMessage());
             }
         }
         else if (DML_INSERT == operation){
          
             try {
         
                 setPiDocNumber(new oracle.jbo.domain.Number(getSrNoString())); 
                 setCreationDate((Date)Date.getCurrentDate());  
                 setCreatedBy(new oracle.jbo.domain.Number(user));
                
                
                
             } catch (SQLException f) {
                 ;
             }
         }

 
 /*        if(operation == DML_INSERT){
          setPiDocNumber(new oracle.jbo.domain.Number(getSrNoString()));    
               }
*/
     super.doDML(operation, e);
     }

}
